name: Update gist
on:
  push:
    branches:
      [ main, dev, master ]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 99928f5c10e3656b047b7d207e6d513a
          TIMEZONE: Asia/Seoul
